# Generated by Django 2.2.5 on 2020-01-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('Category', models.CharField(default='', max_length=30)),
                ('quantity', models.CharField(default='', max_length=30)),
                ('Description', models.CharField(default='', max_length=30)),
                ('Price', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('Image', models.ImageField(upload_to='food')),
            ],
        ),
        migrations.CreateModel(
            name='add_pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('Category', models.CharField(default='', max_length=30)),
                ('Breed', models.CharField(default='', max_length=30)),
                ('Age', models.CharField(default='', max_length=30)),
                ('Colour', models.CharField(default='', max_length=30)),
                ('size', models.IntegerField(default=0)),
                ('Vaccination', models.CharField(default='', max_length=30)),
                ('Description', models.CharField(default='', max_length=30)),
                ('Price', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('Image', models.ImageField(upload_to='pets')),
                ('type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=30)),
                ('shipping', models.CharField(default='', max_length=30)),
                ('total', models.CharField(default='', max_length=30)),
                ('unitprice', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('item', models.CharField(default='', max_length=30)),
                ('shopid', models.IntegerField(default=0)),
                ('shoppay', models.CharField(default='pending', max_length=30)),
                ('fid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.add_food')),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.add_pets')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('address', models.CharField(default='', max_length=30)),
                ('status1', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_order_pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('services', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add_pets')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='user_order_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('services', models.CharField(default='', max_length=100)),
                ('details', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.add_food')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='paymenttoshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('cartid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.cart_tb')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.AddField(
            model_name='cart_tb',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
        ),
        migrations.CreateModel(
            name='add_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Company', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Location', models.CharField(default='', max_length=30)),
                ('Mobile', models.IntegerField(default=0)),
                ('Facility', models.CharField(default='', max_length=30)),
                ('status1', models.CharField(default='', max_length=30)),
                ('Image', models.ImageField(upload_to='image')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
        migrations.AddField(
            model_name='add_pets',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
        ),
        migrations.AddField(
            model_name='add_food',
            name='fid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.register'),
        ),
    ]
