# Generated by Django 2.2.5 on 2020-01-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order_pets',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='user_order_pets',
            name='uid',
        ),
        migrations.DeleteModel(
            name='user_order_food',
        ),
        migrations.DeleteModel(
            name='user_order_pets',
        ),
    ]
