# Generated by Django 2.2.5 on 2020-01-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200109_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='pid',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.add_pets'),
        ),
    ]
