# Generated by Django 2.2.5 on 2020-01-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200109_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paymenttoshop',
            new_name='paymenttoshop_tb',
        ),
    ]
