# Generated by Django 2.2.5 on 2020-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200109_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Image',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.DeleteModel(
            name='add_shop',
        ),
    ]
