# Generated by Django 2.2.5 on 2020-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200120_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food',
            name='availableqty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='add_pets',
            name='availableqty',
            field=models.CharField(default='', max_length=30),
        ),
    ]
