# Generated by Django 2.2.5 on 2020-01-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200120_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_pets',
            name='availableqty',
        ),
    ]
