# Generated by Django 2.2.5 on 2020-01-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_add_pets_availableqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food',
            name='rating',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='add_pets',
            name='rating',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='review_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=30)),
                ('rating', models.CharField(default='', max_length=30)),
                ('fid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.add_food')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.add_pets')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
