# Generated by Django 2.2.5 on 2020-01-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200121_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_food',
            name='rating',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='rating',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
