# Generated by Django 2.2.5 on 2020-01-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_tb',
            name='cartid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.cart_tb'),
        ),
    ]
