# Generated by Django 2.2.5 on 2020-01-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200122_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_food',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='add_pets',
            name='rating',
        ),
    ]
