# Generated by Django 2.2.5 on 2020-02-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200122_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_food',
            name='Category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='Description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='Price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='availableqty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='rating',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='add_food',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Breed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Colour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='Vaccination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='availableqty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='rating',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_pets',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='item',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='shipping',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='shoppay',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='unitprice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment_tb',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment_tb',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment_tb',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttoshop_tb',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttoshop_tb',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='status1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review_tb',
            name='item',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review_tb',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='vetenery_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(default='', max_length=100)),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
