# Generated by Django 2.2.5 on 2020-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200210_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetenery_tb',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
