# Generated by Django 2.2.5 on 2020-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_vetenery_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetenery_tb',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vetenery_tb',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
